stages:
  logStart:
    pipeline: Indexing\Stage\Log
    args:
      message: "Start Add CMS Pipeline"
  iterateIndexingRecordsBatch:
    pipeline: Pipeline\Iterate # LOOP OVER ALL PROVIDED BATCHES
    args:
      continueOnException: ~
    stages:
      iteratePages:
        pipeline: Pipeline\Iterate
        args:
          continueOnException: ~
        stages:
          processIndexingRecordStart:
            stages:
              registerIndexingRecordToContext:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: "currentIndexingRecord"
              registerPageToContext:
                stages:
                  extractCategory:
                    pipeline: Stage\Extract
                    args:
                      extraction: currentIndexingRecord::getEntity()
                  registerCategory:
                    pipeline: Stage\RegisterContext
                    args:
                      contextKey: "currentPage"
              registerActionToContext:
                stages:
                  extractAction:
                    pipeline: Stage\Extract
                    args:
                      extraction: currentIndexingRecord::getAction()
                  registerAction:
                    pipeline: Stage\RegisterContext
                    args:
                      contextKey: "currentAction"
              registerEntityTypeToContext:
                stages:
                  createEntityType:
                    pipeline: Stage\StaticValue
                    args:
                      value: "KLEVU_CMS"
                  registerEntityType:
                    pipeline: Stage\RegisterContext
                    args:
                      contextKey: "currentEntityType"
          processPage:
            stages:
              createRecord:
                import: transform-page.yml
      processPayload:
        import: Klevu_Indexing::etc/pipeline/process-batch-payload.yml
  logEnd:
    pipeline: Indexing\Stage\Log
    args:
      message: "End Add CMS Pipeline"
