stages:
  logStart:
    pipeline: Indexing\Stage\Log
    args:
      message: "Start Update CMS Pipeline"
  iteratePages:
    pipeline: Pipeline\Iterate
    args:
      continueOnException: ~
    stages:
      processIndexingRecordStart:
        stages:
          registerIndexingRecordToContext:
            pipeline: Stage\RegisterContext
            args:
              contextKey: currentIndexingRecord
          registerCategoryToContext:
            stages:
              extractCategory:
                pipeline: Stage\Extract
                args:
                  extraction: currentIndexingRecord::getEntity()
              registerCategory:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: currentPage
          registerActionToContext:
            stages:
              createAction:
                pipeline: Stage\StaticValue
                args:
                  value: "Update"
              registerAction:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: "currentAction"
          registerEntityTypeToContext:
            stages:
              createEntityType:
                pipeline: Stage\StaticValue
                args:
                  value: "KLEVU_CMS"
              registerEntityType:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: "currentEntityType"
      processPage:
        stages:
          createRecord:
            import: transform-page.yml
  processPayload:
    #        import: Klevu_Indexing::etc/pipeline/process-batch-payload.yml
    import: ../../../module-m2-indexing/etc/pipeline/process-batch-payload.yml
  logEnd:
    pipeline: Indexing\Stage\Log
    args:
      message: "End Update CMS Pipeline"
